import { HACKSAW_API_BASE, HACKSAW_USER_AGENT } from '../api/providers/hacksawShared'
export const PROVIDERS = {
  hacksaw: {
    id: 'hacksaw',
    name: 'Hacksaw Gaming',
    apiBase: HACKSAW_API_BASE,
    userAgent: HACKSAW_USER_AGENT,
    sessionFields: ['token', 'sessionUuid', 'seq'],
    betLevelsSource: 'api',
    continuePolicy: 'instructions-or-win_presentation_complete',
    supportsMultiCurrencySameSlot: false,
  },
  pragmatic: {
    id: 'pragmatic',
    name: 'Pragmatic Play',
    supportsMultiCurrencySameSlot: true,
    gameServicePathV4: '/gs2c/ge/v4/gameService',
    gameServicePathV3: '/gs2c/ge/v3/gameService',
    zeroDecimalCurrencies: ['idr', 'jpy', 'krw', 'vnd'],
    sessionFields: ['mgckey', 'symbol', 'host', 'index', 'counter'],
    betLevelsSource: 'doInit-parse',
    cUnitPolicy: 'minor-or-zero-decimal',
  },
  stakeEngine: {
    id: 'stakeEngine',
    name: 'Stake Engine',
    supportsMultiCurrencySameSlot: true,
    amountScale: 1000000,
    zeroDecimalCurrencies: ['idr', 'jpy', 'krw', 'vnd'],
    sessionFields: ['sessionID', 'rgsUrl'],
    betLevelsSource: 'config-betLevels',
    playEndpoints: { play: '/wallet/play', endRound: '/wallet/end-round', authenticate: '/wallet/authenticate' },
    bonusResolution: 'server-autoplay',
    instantBonus: true,
  },
  '1000lakes': {
    id: '1000lakes',
    name: '1000 Lakes Studios',
    aliasOf: 'stakeEngine',
  },
  nolimit: {
    id: 'nolimit',
    name: 'Nolimit City',
    supportsMultiCurrencySameSlot: true,
    protocol: '@nolimit/game-communication@0.1.48',
    requiresExtPlayerKey: true,
    modes: { standard: 'CAP_MODE_STANDARD' },
    freeSpinModes: ['NORMAL_AVALANCHE', 'FREESPIN_AVALANCHE', 'FREESPIN_COOL_AVALANCHE'],
    betLevelsSource: 'sessionConfig.availableBetLevels',
  },
  paperclip: {
    id: 'paperclip',
    name: 'Paperclip',
    aliasOf: 'stakeEngine',
    bonusResolution: 'server-autoplay',
    instantBonus: true,
  },
  relax: {
    id: 'relax',
    name: 'Relax Gaming',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  blueprint: {
    id: 'blueprint',
    name: 'Blueprint Gaming',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  endorphina: {
    id: 'endorphina',
    name: 'Endorphina',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  thunderkick: {
    id: 'thunderkick',
    name: 'Thunderkick',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  netent: {
    id: 'netent',
    name: 'NetEnt',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  gameart: {
    id: 'gameart',
    name: 'GameArt',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  push: {
    id: 'push',
    name: 'Push Gaming',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  btg: {
    id: 'btg',
    name: 'Big Time Gaming',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  oak: {
    id: 'oak',
    name: 'OAK',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  redtiger: {
    id: 'redtiger',
    name: 'Red Tiger',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  playngo: {
    id: 'playngo',
    name: 'Play’n GO',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  octoplay: {
    id: 'octoplay',
    name: 'Octoplay',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  peterandsons: {
    id: 'peterandsons',
    name: 'Peter & Sons',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  shady: {
    id: 'shady',
    name: 'Shady',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  shuffle: {
    id: 'shuffle',
    name: 'Shuffle',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  titan: {
    id: 'titan',
    name: 'Titan',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  twist: {
    id: 'twist',
    name: 'Twist',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  popiplay: {
    id: 'popiplay',
    name: 'Popiplay',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  helio: {
    id: 'helio',
    name: 'Helio',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  samurai: {
    id: 'samurai',
    name: 'Samurai',
    sessionFields: ['token', 'gameId', 'host'],
    betLevelsSource: 'sessionConfig',
  },
  clawbuster: {
    id: 'clawbuster',
    name: 'Claw Buster',
    sessionFields: ['token', 'playUrl'],
    betLevelsSource: 'sessionConfig',
    betDisplayDivisorSlots: ['clawbuster-3-claws-of-leprechaun-gold-hold-and-win'],
    betDisplayDivisor: 100,
  },
  // aliases
  rt: { id: 'rt', name: 'Red Tiger alias', aliasOf: 'redtiger' },
  png: { id: 'png', name: 'Play’n GO alias', aliasOf: 'playngo' },
  octo: { id: 'octo', name: 'Octoplay alias', aliasOf: 'octoplay' },
  peter: { id: 'peter', name: 'Peter & Sons alias', aliasOf: 'peterandsons' },
  netentws: { id: 'netentws', name: 'NetEnt WS alias', aliasOf: 'netent' },
  tl: { id: 'tl', name: '1000 Lakes alias', aliasOf: 'stakeEngine' },
  stc: { id: 'stc', name: 'Stake Engine alias', aliasOf: 'stakeEngine' },
  popi: { id: 'popi', name: 'Popiplay alias', aliasOf: 'popiplay' },
}

/** Prüft ob Provider denselben Slot in verschiedenen Währungen parallel erlaubt */
export function supportsMultiCurrencySameSlot(providerId) {
  const p = PROVIDERS[providerId] || {}
  const base = p.aliasOf ? (PROVIDERS[p.aliasOf] || {}) : p
  return base.supportsMultiCurrencySameSlot !== false
}
