/**
 * Unterstützte Slots – zugeordnet zu Providern
 * slug = Stake-Game-Slug (für startThirdPartySession)
 * providerId = Referenz auf Provider-Registry
 */
export const SUPPORTED_SLOTS = [
  // Hacksaw Gaming (Web-API, direkt unterstützt)
  { slug: 'hacksaw-2-wild-2-die', name: '2 Wild 2 Die', providerId: 'hacksaw' },
  { slug: 'hacksaw-alpha-eagle', name: 'Alpha Eagle', providerId: 'hacksaw' },
  { slug: 'hacksaw-army-of-ares', name: 'Army of Ares', providerId: 'hacksaw' },
  { slug: 'hacksaw-beam-boys', name: 'Beam Boys', providerId: 'hacksaw' },
  { slug: 'hacksaw-beast-below', name: 'Beast Below', providerId: 'hacksaw' },
  { slug: 'hacksaw-benny-the-beer', name: 'Benny the Beer', providerId: 'hacksaw' },
  { slug: 'hacksaw-bloodthirst', name: 'Bloodthirst', providerId: 'hacksaw' },
  { slug: 'hacksaw-born-wild', name: 'Born Wild', providerId: 'hacksaw' },
  { slug: 'hacksaw-break-bones', name: 'Break Bones', providerId: 'hacksaw' },
  { slug: 'hacksaw-buffalo-stack-n-sync', name: 'Buffalo Stack n Sync', providerId: 'hacksaw' },
  { slug: 'hacksaw-bullets-and-bounty', name: 'Bullets and Bounty', providerId: 'hacksaw' },
  { slug: 'hacksaw-canny-the-can-and-the-book-of-time', name: 'Canny the Can and the Book of Time', providerId: 'hacksaw' },
  { slug: 'hacksaw-cash-crew', name: 'Cash Crew', providerId: 'hacksaw' },
  { slug: 'hacksaw-chaos-crew', name: 'Chaos Crew', providerId: 'hacksaw' },
  { slug: 'hacksaw-chaos-crew-2', name: 'Chaos Crew 2', providerId: 'hacksaw' },
  { slug: 'hacksaw-chaos-crew-3', name: 'Chaos Crew 3', providerId: 'hacksaw' },
  { slug: 'hacksaw-cubes', name: 'Cubes', providerId: 'hacksaw' },
  { slug: 'hacksaw-cubes-2', name: 'Cubes 2', providerId: 'hacksaw' },
  { slug: 'hacksaw-cursed-crypt', name: 'Cursed Crypt', providerId: 'hacksaw' },
  { slug: 'hacksaw-cursed-seas', name: 'Cursed Seas', providerId: 'hacksaw' },
  { slug: 'hacksaw-densho', name: 'Densho', providerId: 'hacksaw' },
  { slug: 'hacksaw-donny-and-danny', name: 'Donny and Danny', providerId: 'hacksaw' },
  { slug: 'hacksaw-dragon-s-domain', name: "Dragon's Domain", providerId: 'hacksaw' },
  { slug: 'hacksaw-dork-unit', name: 'Dork Unit', providerId: 'hacksaw' },
  { slug: 'hacksaw-eye-of-the-panda', name: 'Eye of the Panda', providerId: 'hacksaw' },
  { slug: 'hacksaw-evil-eyes', name: 'Evil Eyes', providerId: 'hacksaw' },
  { slug: 'hacksaw-fist-of-destruction', name: 'Fist of Destruction', providerId: 'hacksaw' },
  { slug: 'hacksaw-fire-my-laser', name: 'Fire my Laser', providerId: 'hacksaw' },
  { slug: 'hacksaw-frutz', name: 'Frutz', providerId: 'hacksaw' },
  { slug: 'hacksaw-get-the-cheese', name: 'Get the Cheese', providerId: 'hacksaw' },
  { slug: 'hacksaw-gladiator-legends', name: 'Gladiator Legends', providerId: 'hacksaw' },
  { slug: 'hacksaw-jaws-of-justice', name: 'Jaws of Justice', providerId: 'hacksaw' },
  { slug: 'hacksaw-joker-bombs', name: 'Joker Bombs', providerId: 'hacksaw' },
  { slug: 'hacksaw-keep-em', name: "Keep'em", providerId: 'hacksaw' },
  { slug: 'hacksaw-klowns', name: 'Klowns', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-bandit', name: 'Le Bandit', providerId: 'hacksaw', betLevels: [1100, 2200, 4400, 6600, 8800, 11000, 13200, 15400, 17600, 19800, 22000, 33000, 44000, 55000, 66000, 77000, 88000, 99000, 110000, 165000, 220000, 275000, 330000, 385000, 440000, 495000, 550000] },
  { slug: 'hacksaw-le-fisherman', name: 'Le Fisherman', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-pharaoh', name: 'Le Pharaoh', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-king', name: 'Le King', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-viking', name: 'Le Viking', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-zeus', name: 'Le Zeus', providerId: 'hacksaw' },
  { slug: 'hacksaw-life-and-death', name: 'Life and Death', providerId: 'hacksaw' },
  { slug: 'hacksaw-marlin-masters', name: 'Marlin Masters', providerId: 'hacksaw' },
  { slug: 'hacksaw-mayan-stackways', name: 'Mayan Stackways', providerId: 'hacksaw' },
  { slug: 'hacksaw-mines', name: 'Mines', providerId: 'hacksaw' },
  { slug: 'hacksaw-om-nom', name: 'Om Nom', providerId: 'hacksaw' },
  { slug: 'hacksaw-plinko', name: 'Plinko', providerId: 'hacksaw' },
  { slug: 'hacksaw-rip-city', name: 'RIP City', providerId: 'hacksaw' },
  { slug: 'hacksaw-ronin-stackways', name: 'Ronin Stackways', providerId: 'hacksaw' },
  { slug: 'hacksaw-snow-slingers', name: 'Snow Slingers', providerId: 'hacksaw' },
  { slug: 'hacksaw-stormforged', name: 'Stormforged', providerId: 'hacksaw' },
  { slug: 'hacksaw-stack-em', name: 'Stack Em', providerId: 'hacksaw' },
  { slug: 'hacksaw-storm-summoning', name: 'Storm Summoning', providerId: 'hacksaw' },
  { slug: 'hacksaw-six-six-six', name: 'Six Six Six', providerId: 'hacksaw' },
  { slug: 'hacksaw-slayers-inc', name: 'Slayer Inc', providerId: 'hacksaw' },
  { slug: 'hacksaw-wanted-dead-or-a-wild', name: 'Wanted Dead or a Wild', providerId: 'hacksaw' },
  // Stake Engine – Slots von Stakes eigener Engine
  { slug: 'blackcoffeestudios-big-lunker-bass-clusters', name: 'Big Lunker Bass Clusters', providerId: 'stakeEngine' },
  { slug: 'blackcoffeestudios-big-lunker-bass-lightning', name: 'Big Lunker Bass Lightning', providerId: 'stakeEngine' },
  { slug: 'evoslot-eddies-vaults', name: "Eddie's Vaults", providerId: 'stakeEngine' },
  { slug: 'creativecity-chocolate-factory', name: 'Chocolate Factory', providerId: 'stakeEngine' },
  { slug: 'valkyrie-lokis-vault', name: "Loki's Vault", providerId: 'stakeEngine' },
  { slug: 'dbushgaming-cyber-samurai-the-last-code', name: 'Cyber Samurai The Last Code', providerId: 'stakeEngine' },
  // Pragmatic Play – Bet-Levels kommen aus doInit (währungsabhängig)
  { slug: 'pragmatic-play-sugar-rush-1000', name: 'Sugar Rush 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-boom', name: 'Big Bass Boom', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-frightening-frankie', name: 'Frightening Frankie', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mermaids-treasure-trove', name: 'Mermaids Treasure Trove', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-captain-kraken-megaways', name: 'Captain Kraken Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fortune-of-olympus', name: 'Fortune of Olympus', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mahjong-wins-super-scatter', name: 'Mahjong Wins Super Scatter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-halloween-3', name: 'Big Bass Halloween 3', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-triple-pot-gold', name: 'Triple Pot Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mummys-jewels', name: "Mummy's Jewels", providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cyberheist-city', name: 'Cyberheist City', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-el-huaso-suertudo', name: 'El Huaso Suertudo', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-rush-bonanza', name: 'Sweet Rush Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bee-keeper', name: 'Bee Keeper', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dragon-tiger-fortunes', name: 'Dragon Tiger Fortunes', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-west-gold-blazing-bounty', name: 'Wild West Gold Blazing Bounty', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gold-portals', name: 'Gold Portals', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-argonauts', name: 'Argonauts', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lava-balls', name: 'Lava Balls', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-john-hunter-and-the-book-of-tut', name: 'John Hunter and the Book of Tut', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-rush', name: 'Sugar Rush', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus', name: 'Gates of Olympus', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-bonanza', name: 'Big Bass Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house', name: 'The Dog House', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-bonanza', name: 'Sweet Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-west-gold', name: 'Wild West Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fruit-party', name: 'Fruit Party', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-great-rhino-megaways', name: 'Great Rhino Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-starlight-princess', name: 'Starlight Princess', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-power-of-thor-megaways', name: 'Power of Thor Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-strike', name: 'Fire Strike', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-diamond-strike', name: 'Diamond Strike', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-aztec-gems', name: 'Aztec Gems', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hot-fiesta', name: 'Hot Fiesta', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-joker-king', name: 'Joker King', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chilli-heat', name: 'Chilli Heat', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-money-train-3', name: 'Money Train 3', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-5-lions-megaways', name: '5 Lions Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-buffalo-king-megaways', name: 'Buffalo King Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-eye-of-cleopatra', name: 'Eye of Cleopatra', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gold-rush', name: 'Gold Rush', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pyramid-bonanza', name: 'Pyramid Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dance-party', name: 'Dance Party', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-monkey-warrior', name: 'Monkey Warrior', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-romeo-and-juliet', name: 'Romeo and Juliet', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-treasure-wild', name: 'Treasure Wild', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-vampires-vs-wolves', name: 'Vampires vs Wolves', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lucky-lightning', name: 'Lucky Lightning', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cash-bonanza', name: 'Cash Bonanza', providerId: 'pragmatic' },
  // +434 aus pragmatic&hacksaw.csv (Pragmatic + Hacksaw)
  { slug: 'pragmatic-play-sweet-bonanza-1000', name: 'Sweet Bonanza 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus-1000', name: 'Gates Of Olympus 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus-super-scatter', name: 'Gates Of Olympus Super Scatter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-3-magic-eggs', name: '3 Magic Eggs', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-stampede-ultimate', name: 'Fire Stampede Ultimate', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-rush-super-scatter', name: 'Sugar Rush Super Scatter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-rock-and-roll', name: 'Big Bass Rock And Roll', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-super-tiki-strike', name: 'Super Tiki Strike', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-zeus-vs-hades-gods-of-war-250', name: 'Zeus Vs Hades Gods Of War 250', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-zeus-vs-hades-gods-of-war', name: 'Zeus Vs Hades Gods Of War', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gold-party', name: 'Gold Party', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-5-lions-megaways-2', name: '5 Lions Megaways 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-splash-1000', name: 'Big Bass Splash 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-knights-vs-barbarians', name: 'Knights Vs Barbarians', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-transylvania-mania', name: 'Transylvania Mania', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-fiesta', name: 'Sweet Fiesta', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-starlight-princess-1000', name: 'Starlight Princess 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gold-party-2-after-hours', name: 'Gold Party 2 After Hours', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-splash', name: 'Big Bass Splash', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-mansion-megaways', name: 'The Dog Mansion Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-juicy-fruits', name: 'Juicy Fruits', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lucky-phoenix-megaways', name: 'Lucky Phoenix Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-angel-vs-sinner-eternal-battle', name: 'Angel Vs Sinner Eternal Battle', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-starlight-princess-super-scatter', name: 'Starlight Princess Super Scatter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-5-lions-megaway', name: '5 Lions Megaway', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pompeii-megareels-megaways', name: 'Pompeii Megareels Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sky-bounty', name: 'Sky Bounty', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-bonanza-super-scatter', name: 'Sweet Bonanza Super Scatter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jewel-bonanza', name: 'Jewel Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-floating-dragon-wild-horses', name: 'Floating Dragon Wild Horses', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-bonanza-1000', name: 'Big Bass Bonanza 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bigger-barn-house-bonanza', name: 'Bigger Barn House Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-3-buzzing-wilds', name: '3 Buzzing Wilds', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-club-tropicana-happy-hour', name: 'Club Tropicana Happy Hour', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus-xmas-1000', name: 'Gates Of Olympus Xmas 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cleocatra', name: 'Cleocatra', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-bonanza-1000-dice', name: 'Sweet Bonanza 1000 Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-madame-mystique-megaways', name: 'Madame Mystique Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wisdom-of-athena-1000', name: 'Wisdom Of Athena 1000', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-boxing-bonus-round', name: 'Big Bass Boxing Bonus Round', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bison-spirit', name: 'Bison Spirit', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-floats-my-boat', name: 'Big Bass Floats My Boat', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-reel-repeat', name: 'Big Bass Reel Repeat', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-megaways', name: 'The Dog House Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-secrets-of-the-golden-lake', name: 'Big Bass Secrets Of The Golden Lake', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-club-tropicana', name: 'Club Tropicana', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-supreme-powernudge', name: 'Sugar Supreme Powernudge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-brick-house-bonanza', name: 'Brick House Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pirates-pub', name: 'Pirates Pub', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hot-tuna', name: 'Hot Tuna', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-portals', name: 'Fire Portals', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bigger-bass-splash', name: 'Bigger Bass Splash', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-and-the-gold-ness-monster', name: 'Big Bass And The Gold Ness Monster', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-madame-destiny-megaways', name: 'Madame Destiny Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-zombie-school-megaways', name: 'Zombie School Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-blitz-boom', name: 'Candy Blitz Boom', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-amazon-xtreme', name: 'Big Bass Amazon Xtreme', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dragon-hero', name: 'Dragon Hero', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-thunder-vs-underworld', name: 'Thunder Vs Underworld', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-halloween', name: 'Big Bass Halloween', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-vegas-double-down-deluxe', name: 'Big Bass Vegas Double Down Deluxe', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-muertos-multiplier-megaways', name: 'Muertos Multiplier Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-no-dog-left-behind', name: 'The Dog House No Dog Left Behind', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-vampy-party', name: 'Vampy Party', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-twist', name: 'Sugar Twist', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-mission-fishin', name: 'Big Bass Mission Fishin', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gems-bonanza', name: 'Gems Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wisdom-of-athena-1000-xmas', name: 'Wisdom Of Athena 1000 Xmas', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-multihold', name: 'The Dog House Multihold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-west-bounty', name: 'Wild West Bounty', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-merlins-madness-megaways', name: 'Merlins Madness Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-bonanza-xmas', name: 'Sweet Bonanza Xmas', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hand-of-midas-2', name: 'Hand Of Midas 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-angel-vs-sinner', name: 'Angel Vs Sinner', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-halloween-2', name: 'Big Bass Halloween 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-zombie-carnival', name: 'Zombie Carnival', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-juan', name: 'Big Juan', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-wild-riches-returns', name: 'Wild Wild Riches Returns', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-stampede-2', name: 'Fire Stampede 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-christmas-bash', name: 'Big Bass Christmas Bash', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-west-gold-megaways', name: 'Wild West Gold Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fish-eye', name: 'Fish Eye', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-wild-gang', name: 'The Wild Gang', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-rush-xmas', name: 'Sugar Rush Xmas', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-hades', name: 'Gates Of Hades', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-super-gummy-strike', name: 'Super Gummy Strike', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-muttley-crew', name: 'The Dog House Muttley Crew', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-royal-hunt', name: 'The Dog House Royal Hunt', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus-1000-dice', name: 'Gates Of Olympus 1000 Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-juicy-fruits-multihold', name: 'Juicy Fruits Multihold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bloody-dawn', name: 'Bloody Dawn', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-craze', name: 'Sweet Craze', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-excalibur-unleashed', name: 'Excalibur Unleashed', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-bonanza-dice', name: 'Sweet Bonanza Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wheel-of-happiness', name: 'Wheel Of Happiness', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-zeus-vs-typhon', name: 'Zeus Vs Typhon', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-xmas-xtreme', name: 'Big Bass Xmas Xtreme', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-witch-heart-megaways', name: 'Witch Heart Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-christmas-frozen-lake', name: 'Big Bass Christmas Frozen Lake', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-dog-house-dog-or-alive', name: 'The Dog House Dog Or Alive', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-christmas-big-bass-bonanza', name: 'Christmas Big Bass Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-power-of-merlin-megaways', name: 'Power Of Merlin Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-peppes-pepperoni-pizza-plaza', name: 'Peppes Pepperoni Pizza Plaza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-bison-charge', name: 'Wild Bison Charge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-monster-superlanche', name: 'Monster Superlanche', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fruit-party-2', name: 'Fruit Party 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-hand-of-midas', name: 'The Hand Of Midas', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-day-at-the-races', name: 'Big Bass Day At The Races', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-fallen', name: 'Book Of Fallen', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-twilight-princess', name: 'Twilight Princess', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-hold-and-spinner', name: 'Big Bass Hold And Spinner', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pizza-pizza-pizza', name: 'Pizza Pizza Pizza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bandit-megaways', name: 'Bandit Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-tut', name: 'Book Of Tut', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-starlight-christmas', name: 'Starlight Christmas', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bigger-bass-blizzard-christmas-catch', name: 'Bigger Bass Blizzard Christmas Catch', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-congo-cash-xl', name: 'Congo Cash Xl', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-hop-drop', name: 'Wild Hop Drop', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-yeti-quest', name: 'Yeti Quest', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-5-lions-reborn', name: '5 Lions Reborn', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sticky-bees', name: 'Sticky Bees', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-santa-s-wonderland', name: 'Santa S Wonderland', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-7-clovers-of-fortune', name: '7 Clovers Of Fortune', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-wild-riches-megaways', name: 'Wild Wild Riches Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-peak-power', name: 'Peak Power', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-5-frozen-charms-megaways', name: '5 Frozen Charms Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sugar-rush-dice', name: 'Sugar Rush Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mining-rush', name: 'Mining Rush', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-release-the-kraken', name: 'Release The Kraken', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-tiny-toads', name: 'Tiny Toads', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-bonanza-3-reeler', name: 'Big Bass Bonanza 3 Reeler', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-release-the-kraken-megaways', name: 'Release The Kraken Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-blitz', name: 'Candy Blitz', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-return-to-the-races', name: 'Big Bass Return To The Races', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chicken-drop', name: 'Chicken Drop', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-extra-juicy-megaways', name: 'Extra Juicy Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-anaconda-gold', name: 'Anaconda Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-queenie', name: 'Queenie', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-magician-s-secrets', name: 'Magician S Secrets', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-wildebeest-wins', name: 'Wild Wildebeest Wins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jewel-rush', name: 'Jewel Rush', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-infective-wild', name: 'Infective Wild', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-black-bull', name: 'Black Bull', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-heart-of-cleopatra', name: 'Heart Of Cleopatra', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-buffalo-king-untamed-megaways', name: 'Buffalo King Untamed Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fortunes-of-aztec', name: 'Fortunes Of Aztec', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-viking-forge', name: 'Viking Forge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bingo-mania', name: 'Bingo Mania', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-olympus-dice', name: 'Gates Of Olympus Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wisdom-of-athena', name: 'Wisdom Of Athena', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-money-stacks', name: 'Money Stacks', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pandemic-rising', name: 'Pandemic Rising', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-blitz-bombs', name: 'Candy Blitz Bombs', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sleeping-dragon', name: 'Sleeping Dragon', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-big-dawgs', name: 'The Big Dawgs', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-stampede', name: 'Fire Stampede', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-wild-joker', name: 'Wild Wild Joker', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chests-of-cai-shen', name: 'Chests Of Cai Shen', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-samurai-code', name: 'Samurai Code', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-golden-sands', name: 'Book Of Golden Sands', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-forge-of-olympus', name: 'Forge Of Olympus', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-release-the-bison', name: 'Release The Bison', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-rabbit-garden', name: 'Rabbit Garden', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ice-mints', name: 'Ice Mints', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fury-of-odin-megaways', name: 'Fury Of Odin Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-jar-clusters', name: 'Candy Jar Clusters', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bow-of-artemis', name: 'Bow Of Artemis', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-release-the-kraken-2', name: 'Release The Kraken 2', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-christmas-carol-megaways', name: 'Christmas Carol Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-empty-the-bank', name: 'Empty The Bank', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mochimon', name: 'Mochimon', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bounty-hunter', name: 'Bounty Hunter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-nile-fortune', name: 'Nile Fortune', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-floating-dragon-year-of-the-snake', name: 'Floating Dragon Year Of The Snake', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-floating-dragon-dragon-boat-festival', name: 'Floating Dragon Dragon Boat Festival', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-bonanza-keeping-it-reel', name: 'Big Bass Bonanza Keeping It Reel', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wheel-o-gold', name: 'Wheel O Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-monsters', name: 'Book Of Monsters', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-barn-festival', name: 'Barn Festival', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-rocket-blast-megaways', name: 'Rocket Blast Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-oracle-of-gold', name: 'Oracle Of Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-curse-of-the-werewolf-megaways', name: 'Curse Of The Werewolf Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-santas-great-gifts', name: 'Santas Great Gifts', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-eye-of-spartacus', name: 'Eye Of Spartacus', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wildies', name: 'Wildies', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-luckys-wild-pub', name: 'Luckys Wild Pub', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-tut-respin', name: 'Book Of Tut Respin', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-blazing-wilds-megaways', name: 'Blazing Wilds Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hot-pepper', name: 'Hot Pepper', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-voodoo-magic', name: 'Voodoo Magic', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-3-dancing-monkeys', name: '3 Dancing Monkeys', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chilli-heat-megaways', name: 'Chilli Heat Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-money-men-megaways', name: 'The Money Men Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fire-archer', name: 'Fire Archer', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mustang-gold-megaways', name: 'Mustang Gold Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-genies-gem-bonanza', name: 'Genies Gem Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fangtastic-freespins', name: 'Fangtastic Freespins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chilli-heat-spicy-spins', name: 'Chilli Heat Spicy Spins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-tropical-tiki', name: 'Tropical Tiki', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-castle-of-fire', name: 'Castle Of Fire', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-waves-of-poseidon', name: 'Waves Of Poseidon', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-starlight-princess-pachi', name: 'Starlight Princess Pachi', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jackpot-blaze', name: 'Jackpot Blaze', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-blade-fangs', name: 'Blade Fangs', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gorilla-mayhem', name: 'Gorilla Mayhem', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-floating-dragon-new-year-festival-ultra-megaways-hold-spin', name: 'Floating Dragon New Year Festival Ultra Megaways Hold Spin', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-finger-lickn-free-spins', name: 'Finger Lickn Free Spins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dragon-gold-88', name: 'Dragon Gold 88', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-crank-it-up', name: 'Crank It Up', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-day-of-dead', name: 'Day Of Dead', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-tut-megaways', name: 'Book Of Tut Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ripe-rewards', name: 'Ripe Rewards', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-blitz-super-wheel', name: 'Blitz Super Wheel', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fat-panda', name: 'Fat Panda', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-volcano-goddess', name: 'Volcano Goddess', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-beach-party', name: 'Wild Beach Party', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sumo-supreme-megaways', name: 'Sumo Supreme Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cash-chips', name: 'Cash Chips', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-resurrecting-riches', name: 'Resurrecting Riches', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wolf-gold-4-pack', name: 'Wolf Gold 4 Pack', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fruity-treats', name: 'Fruity Treats', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-kingdom', name: 'Sweet Kingdom', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wolf-gold-ultimate', name: 'Wolf Gold Ultimate', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mustang-trail', name: 'Mustang Trail', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-santas-slay', name: 'Santas Slay', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gold-oasis', name: 'Gold Oasis', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ice-lobster', name: 'Ice Lobster', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pot-of-fortune', name: 'Pot Of Fortune', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-temujin-treasures', name: 'Temujin Treasures', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fruit-party-dice', name: 'Fruit Party Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-santas-xmas-rush', name: 'Santas Xmas Rush', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-aztec-smash', name: 'Aztec Smash', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-saray-ruyasi', name: 'Saray Ruyasi', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-frozen-tropics', name: 'Frozen Tropics', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-raging-waterfall-megaways', name: 'Raging Waterfall Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gates-of-valhalla', name: 'Gates Of Valhalla', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-floating-dragon-hold-spin-megaways', name: 'Floating Dragon Hold Spin Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-yum-yum-powerways', name: 'Yum Yum Powerways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-rise-of-giza-powernudge', name: 'Rise Of Giza Powernudge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-might-of-freya-megaways', name: 'Might Of Freya Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-barnyard-megahays-megaways', name: 'Barnyard Megahays Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-bonanza-reel-action', name: 'Big Bass Bonanza Reel Action', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mysterious-egypt', name: 'Mysterious Egypt', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-book-of-vikings', name: 'Book Of Vikings', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sweet-powernudge', name: 'Sweet Powernudge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-crystal-caverns-megaways', name: 'Crystal Caverns Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-bermuda-riches', name: 'Bermuda Riches', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hundreds-and-thousands', name: 'Hundreds And Thousands', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-irish-crown', name: 'Irish Crown', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-you-can-piggy-bank-on-it', name: 'You Can Piggy Bank On It', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-corner', name: 'Candy Corner', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pub-kings', name: 'Pub Kings', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-alien-invaders', name: 'Alien Invaders', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-heroic-spins', name: 'Heroic Spins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-rainbow-reels', name: 'Rainbow Reels', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-eternal-empress-freeze-time', name: 'Eternal Empress Freeze Time', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-oodles-of-noodles', name: 'Oodles Of Noodles', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-running-sushi', name: 'Running Sushi', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-firebird-spirit', name: 'Firebird Spirit', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-odds-on-winner', name: 'Odds On Winner', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-savannah-legend', name: 'Savannah Legend', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-piggy-bankers', name: 'Piggy Bankers', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-candy-stars', name: 'Candy Stars', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-alter-ego', name: 'The Alter Ego', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-wild-pearls', name: 'Wild Wild Pearls', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-chase-for-glory', name: 'Chase For Glory', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cowboy-coins', name: 'Cowboy Coins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-beware-the-deep-megaways', name: 'Beware The Deep Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-aztec-blaze', name: 'Aztec Blaze', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-aztec-powernudge', name: 'Aztec Powernudge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cash-box', name: 'Cash Box', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-badge-blitz', name: 'Badge Blitz', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-sword-of-ares', name: 'Sword Of Ares', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-bass-hold-spinner-megaways', name: 'Big Bass Hold Spinner Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-star-bounty', name: 'Star Bounty', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-spellbinding-mystery', name: 'Spellbinding Mystery', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-money-stacks-megaways', name: 'Money Stacks Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gem-trio', name: 'Gem Trio', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-magic-money-maze', name: 'Magic Money Maze', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mighty-munching-melons', name: 'Mighty Munching Melons', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-medusas-stone', name: 'Medusas Stone', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-temple-guardians', name: 'Temple Guardians', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gravity-bonanza', name: 'Gravity Bonanza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mystery-mice', name: 'Mystery Mice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-greedy-fortune-pig', name: 'Greedy Fortune Pig', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-drago-jewels-of-fortune', name: 'Drago Jewels Of Fortune', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-reel-banks', name: 'Reel Banks', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-heist-for-the-golden-nuggets', name: 'Heist For The Golden Nuggets', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-revenge-of-loki-megaways', name: 'Revenge Of Loki Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-wild-booster', name: 'Wild Booster', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fortune-hit-n-roll', name: 'Fortune Hit N Roll', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jumbo-safari', name: 'Jumbo Safari', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-john-hunter-and-galileos-secrets', name: 'John Hunter And Galileos Secrets', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-mystery-of-the-orient', name: 'Mystery Of The Orient', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gem-fire-fortune', name: 'Gem Fire Fortune', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pinup-girls', name: 'Pinup Girls', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dwarf-dragon', name: 'Dwarf Dragon', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-escape-the-pyramid-fire-ice', name: 'Escape The Pyramid Fire Ice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gods-of-giza', name: 'Gods Of Giza', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-pirate-gold-deluxe', name: 'Pirate Gold Deluxe', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-aztec-treasure-hunt', name: 'Aztec Treasure Hunt', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-goblin-heist-powernudge', name: 'Goblin Heist Powernudge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ride-the-lightning', name: 'Ride The Lightning', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lamp-of-infinity', name: 'Lamp Of Infinity', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-knight-king', name: 'The Knight King', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-majestic-express-gold-run', name: 'Majestic Express Gold Run', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ancient-island-megaways', name: 'Ancient Island Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-secret-city-gold', name: 'Secret City Gold', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-big-burger-load-it-up-with-xtra-cheese', name: 'Big Burger Load It Up With Xtra Cheese', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-demon-pots', name: 'Demon Pots', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-spin-score-megaways', name: 'Spin Score Megaways', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-devilicious', name: 'Devilicious', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gears-of-horus', name: 'Gears Of Horus', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-fonzos-feline-fortunes', name: 'Fonzos Feline Fortunes', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-himalayan-wild', name: 'Himalayan Wild', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dragon-king-hot-pots', name: 'Dragon King Hot Pots', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hellvis-wild', name: 'Hellvis Wild', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-hot-to-burn-7-deadly-free-spins', name: 'Hot To Burn 7 Deadly Free Spins', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-8-golden-dragon-challenge', name: '8 Golden Dragon Challenge', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-north-guardians', name: 'North Guardians', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-moleionaire', name: 'Moleionaire', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-red-hot-luck', name: 'Red Hot Luck', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-strawberry-cocktail', name: 'Strawberry Cocktail', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lobster-bobs-crazy-crab-shack', name: 'Lobster Bobs Crazy Crab Shack', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-penguins-christmas-party-time', name: 'Penguins Christmas Party Time', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-dynamite-diggin-doug', name: 'Dynamite Diggin Doug', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-year-of-the-dragon-king', name: 'Year Of The Dragon King', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-country-farming', name: 'Country Farming', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-african-elephant', name: 'African Elephant', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-diamond-cascade', name: 'Diamond Cascade', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jackpot-hunter', name: 'Jackpot Hunter', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-rise-of-pyramids', name: 'Rise Of Pyramids', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-cyclops-smash', name: 'Cyclops Smash', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-gem-elevator', name: 'Gem Elevator', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lobster-bobs-sea-food-and-win-it', name: 'Lobster Bobs Sea Food And Win It', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-ding-dong-christmas-bells', name: 'Ding Dong Christmas Bells', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-forging-wilds', name: 'Forging Wilds', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-the-conqueror', name: 'The Conqueror', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-kingdom-of-the-dead', name: 'Kingdom Of The Dead', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-jane-hunter-and-the-mask-of-montezuma', name: 'Jane Hunter And The Mask Of Montezuma', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-tic-tac-take', name: 'Tic Tac Take', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-money-stacks-dice', name: 'Money Stacks Dice', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-lokis-riches', name: 'Lokis Riches', providerId: 'pragmatic' },
  { slug: 'pragmatic-play-happy-hooves', name: 'Happy Hooves', providerId: 'pragmatic' },
  // Hacksaw (aus CSV)
  { slug: 'hacksaw-sun-princess', name: 'Sun Princess', providerId: 'hacksaw' },
  { slug: 'hacksaw-shaolin-master', name: 'Shaolin Master', providerId: 'hacksaw' },
  { slug: 'hacksaw-immortal-desire', name: 'Immortal Desire', providerId: 'hacksaw' },
  { slug: 'hacksaw-toshi-ways-club', name: 'Toshi Ways Club', providerId: 'hacksaw' },
  { slug: 'hacksaw-donny-dough', name: 'Donny Dough', providerId: 'hacksaw' },
  { slug: 'hacksaw-ultimate-slot-of-america', name: 'Ultimate Slot Of America', providerId: 'hacksaw' },
  { slug: 'hacksaw-rusty-curly', name: 'Rusty Curly', providerId: 'hacksaw' },
  { slug: 'hacksaw-feel-the-beat', name: 'Feel The Beat', providerId: 'hacksaw' },
  { slug: 'hacksaw-undead-fortune', name: 'Undead Fortune', providerId: 'hacksaw' },
  { slug: 'hacksaw-reign-of-rome', name: 'Reign Of Rome', providerId: 'hacksaw' },
  { slug: 'hacksaw-tasty-treats', name: 'Tasty Treats', providerId: 'hacksaw' },
  { slug: 'hacksaw-miami-mayhem', name: 'Miami Mayhem', providerId: 'hacksaw' },
  { slug: 'hacksaw-frkn-bananas', name: 'Frkn Bananas', providerId: 'hacksaw' },
  { slug: 'hacksaw-xmas-drop', name: 'Xmas Drop', providerId: 'hacksaw' },
  { slug: 'hacksaw-temple-of-torment', name: 'Temple Of Torment', providerId: 'hacksaw' },
  { slug: 'hacksaw-franks-farm', name: 'Franks Farm', providerId: 'hacksaw' },
  { slug: 'hacksaw-rise-of-ymir', name: 'Rise Of Ymir', providerId: 'hacksaw' },
  { slug: 'hacksaw-sixsixsix', name: 'Six Six Six', providerId: 'hacksaw' },
  { slug: 'hacksaw-marlin-masters-the-big-haul', name: 'Marlin Masters The Big Haul', providerId: 'hacksaw' },
  { slug: 'hacksaw-rocket-reels', name: 'Rocket Reels', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-cowboy', name: 'Le Cowboy', providerId: 'hacksaw' },
  { slug: 'hacksaw-deal-with-death', name: 'Deal With Death', providerId: 'hacksaw' },
  { slug: 'hacksaw-eye-of-medusa', name: 'Eye Of Medusa', providerId: 'hacksaw' },
  { slug: 'hacksaw-tiger-legends', name: 'Tiger Legends', providerId: 'hacksaw' },
  { slug: 'hacksaw-dragons-domain', name: 'Dragons Domain', providerId: 'hacksaw' },
  { slug: 'hacksaw-donut-division', name: 'Donut Division', providerId: 'hacksaw' },
  { slug: 'hacksaw-king-carrot', name: 'King Carrot', providerId: 'hacksaw' },
  { slug: 'hacksaw-dorks-of-the-deep', name: 'Dorks Of The Deep', providerId: 'hacksaw' },
  { slug: 'hacksaw-vending-machine', name: 'Vending Machine', providerId: 'hacksaw' },
  { slug: 'hacksaw-fighter-pit', name: 'Fighter Pit', providerId: 'hacksaw' },
  { slug: 'hacksaw-hand-of-anubis', name: 'Hand Of Anubis', providerId: 'hacksaw' },
  { slug: 'hacksaw-steam-runners', name: 'Steam Runners', providerId: 'hacksaw' },
  { slug: 'hacksaw-booze-bash', name: 'Booze Bash', providerId: 'hacksaw' },
  { slug: 'hacksaw-orb-of-destiny', name: 'Orb Of Destiny', providerId: 'hacksaw' },
  { slug: 'hacksaw-pray-for-three', name: 'Pray For Three', providerId: 'hacksaw' },
  { slug: 'hacksaw-phoenix-duelreels', name: 'Phoenix Duelreels', providerId: 'hacksaw' },
  { slug: 'hacksaw-dawn-of-kings', name: 'Dawn Of Kings', providerId: 'hacksaw' },
  { slug: 'hacksaw-harvest-wilds', name: 'Harvest Wilds', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-santa', name: 'Le Santa', providerId: 'hacksaw' },
  { slug: 'hacksaw-stormborn', name: 'Stormborn', providerId: 'hacksaw' },
  { slug: 'hacksaw-divine-drop', name: 'Divine Drop', providerId: 'hacksaw' },
  { slug: 'hacksaw-fruit-duel', name: 'Fruit Duel', providerId: 'hacksaw' },
  { slug: 'hacksaw-smoking-dragon', name: 'Smoking Dragon', providerId: 'hacksaw' },
  { slug: 'hacksaw-mighty-masks-nudgereels', name: 'Mighty Masks Nudgereels', providerId: 'hacksaw' },
  { slug: 'hacksaw-book-of-time', name: 'Book Of Time', providerId: 'hacksaw' },
  { slug: 'hacksaw-fear-the-dark', name: 'Fear The Dark', providerId: 'hacksaw' },
  { slug: 'hacksaw-strength-of-hercules', name: 'Strength Of Hercules', providerId: 'hacksaw' },
  { slug: 'hacksaw-magic-piggy', name: 'Magic Piggy', providerId: 'hacksaw' },
  { slug: 'hacksaw-spinman', name: 'Spinman', providerId: 'hacksaw' },
  { slug: 'hacksaw-octo-attack', name: 'Octo Attack', providerId: 'hacksaw' },
  { slug: 'hacksaw-time-spinners', name: 'Time Spinners', providerId: 'hacksaw' },
  { slug: 'hacksaw-toshi-video-club', name: 'Toshi Video Club', providerId: 'hacksaw' },
  { slug: 'hacksaw-aiko-and-the-wind-spirit', name: 'Aiko And The Wind Spirit', providerId: 'hacksaw' },
  { slug: 'hacksaw-outlaws-inc', name: 'Outlaws Inc', providerId: 'hacksaw' },
  { slug: 'hacksaw-hounds-of-hell', name: 'Hounds Of Hell', providerId: 'hacksaw' },
  { slug: 'hacksaw-le-rapper', name: 'Le Rapper', providerId: 'hacksaw' },
  { slug: 'hacksaw-pray-for-six', name: 'Pray For Six', providerId: 'hacksaw' },
  { slug: 'hacksaw-duel-at-dawn', name: 'Duel At Dawn', providerId: 'hacksaw' },
  { slug: 'hacksaw-forest-fortune', name: 'Forest Fortune', providerId: 'hacksaw' },
  { slug: 'hacksaw-dark-summoning', name: 'Dark Summoning', providerId: 'hacksaw' },
  { slug: 'hacksaw-bouncy-bombs', name: 'Bouncy Bombs', providerId: 'hacksaw' },
  { slug: 'hacksaw-danny-dollar', name: 'Danny Dollar', providerId: 'hacksaw' },
  { slug: 'hacksaw-aztec-twist', name: 'Aztec Twist', providerId: 'hacksaw' },
  { slug: 'hacksaw-invictus', name: 'Invictus', providerId: 'hacksaw' },
  { slug: 'hacksaw-xpander', name: 'Xpander', providerId: 'hacksaw' },
  { slug: 'hacksaw-circle-of-life', name: 'Circle Of Life', providerId: 'hacksaw' },
  { slug: 'hacksaw-the-bowery-boys', name: 'The Bowery Boys', providerId: 'hacksaw' },
  { slug: 'hacksaw-cash-quest', name: 'Cash Quest', providerId: 'hacksaw' },
  { slug: 'hacksaw-the-count', name: 'The Count', providerId: 'hacksaw' },
  { slug: 'hacksaw-mystery-motel', name: 'Mystery Motel', providerId: 'hacksaw' },
  { slug: 'hacksaw-warrior-ways', name: 'Warrior Ways', providerId: 'hacksaw' },
  { slug: 'hacksaw-double-rainbow', name: 'Double Rainbow', providerId: 'hacksaw' },
  { slug: 'hacksaw-pug-life', name: 'Pug Life', providerId: 'hacksaw' },
  { slug: 'hacksaw-the-wildwood-curse', name: 'The Wildwood Curse', providerId: 'hacksaw' },
  { slug: 'hacksaw-wishbringer', name: 'Wishbringer', providerId: 'hacksaw' },
  { slug: 'hacksaw-tai-the-toad', name: 'Tai The Toad', providerId: 'hacksaw' },
  { slug: 'hacksaw-gronks-gems', name: 'Gronks Gems', providerId: 'hacksaw' },
  { slug: 'hacksaw-ze-zeus', name: 'Ze Zeus', providerId: 'hacksaw' },
  { slug: 'hacksaw-rainbow-princess', name: 'Rainbow Princess', providerId: 'hacksaw' },
  { slug: 'hacksaw-wings-of-horus', name: 'Wings Of Horus', providerId: 'hacksaw' },
  { slug: 'hacksaw-zeus-ze-zecond', name: 'Zeus Ze Zecond', providerId: 'hacksaw' },
  { slug: 'hacksaw-jelly-slice', name: 'Jelly Slice', providerId: 'hacksaw' },
  { slug: 'hacksaw-freds-food-truck', name: 'Freds Food Truck', providerId: 'hacksaw' },
  { slug: 'hacksaw-rotten', name: 'Rotten', providerId: 'hacksaw' },
  { slug: 'hacksaw-cloud-princess', name: 'Cloud Princess', providerId: 'hacksaw' },
  { slug: 'hacksaw-rad-maxx', name: 'Rad Maxx', providerId: 'hacksaw' },
  { slug: 'hacksaw-drop-em', name: 'Drop Em', providerId: 'hacksaw' },
  { slug: 'hacksaw-hop-n-pop', name: 'Hop N Pop', providerId: 'hacksaw' },
  { slug: 'hacksaw-spear-of-athena', name: 'Spear Of Athena', providerId: 'hacksaw' },
  { slug: 'hacksaw-the-luxe', name: 'The Luxe', providerId: 'hacksaw' },
  // 1000 Lakes Studios (stakeEngine)
  { slug: '1000lakesstudios-flying-finns-1000', name: 'Flying Finns 1000', providerId: 'stakeEngine' },
  // Titan / Twist / Uppercut / Paperclip / Knucklehead (stakeEngine)
  { slug: 'titan-gaming-dojo-duel', name: 'Titan Gaming Dojo Duel', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-duel-of-olympus', name: 'Titan Gaming Duel Of Olympus', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-wicked-brew', name: 'Twist Gaming Wicked Brew', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-pirate-rush', name: 'Titan Gaming Pirate Rush', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-bank-basher', name: 'Twist Gaming Bank Basher', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-magic-1000', name: 'Titan Gaming Magic 1000', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-zeus-god-of-thunder', name: 'Titan Gaming Zeus God Of Thunder', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-hens-night', name: 'Twist Gaming Hens Night', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-million-x', name: 'Titan Gaming Million X', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-puffer-stacks-2', name: 'Titan Gaming Puffer Stacks 2', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-wizard-1000', name: 'Titan Gaming Wizard 1000', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-reel-racing', name: 'Twist Gaming Reel Racing', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-airstrike', name: 'Titan Gaming Airstrike', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-battle-of-gods', name: 'Titan Gaming Battle Of Gods', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-ninja-rabbit', name: 'Titan Gaming Ninja Rabbit', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-dust-devil', name: 'Titan Gaming Dust Devil', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-akimbo-outlaw', name: 'Titan Gaming Akimbo Outlaw', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-pixel-castle', name: 'Twist Gaming Pixel Castle', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-switchcraft', name: 'Titan Gaming Switchcraft', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-sweet-boom', name: 'Titan Gaming Sweet Boom', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-farmageddon', name: 'Titan Gaming Farmageddon', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-www', name: 'Titan Gaming Www', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-eye-of-anubis', name: 'Titan Gaming Eye Of Anubis', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-pixel-farm', name: 'Twist Gaming Pixel Farm', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-realm-of-rats-2', name: 'Twist Gaming Realm Of Rats 2', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-pixel-cafe', name: 'Twist Gaming Pixel Cafe', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-gems', name: 'Titan Gaming Gems', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-underworld', name: 'Titan Gaming Underworld', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-massive-x', name: 'Titan Gaming Massive X', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-realm-of-rats', name: 'Twist Gaming Realm Of Rats', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-the-bandit', name: 'Titan Gaming The Bandit', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-pirates-of-the-dawn', name: 'Titan Gaming Pirates Of The Dawn', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-cult-of-cash', name: 'Twist Gaming Cult Of Cash', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-puffer-stacks', name: 'Titan Gaming Puffer Stacks', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-juicy-harvest', name: 'Titan Gaming Juicy Harvest', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-samurai-dogs', name: 'Twist Gaming Samurai Dogs', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-win-exe', name: 'Twist Gaming Win Exe', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-lost-tribe', name: 'Titan Gaming Lost Tribe', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-boomtown', name: 'Titan Gaming Boomtown', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-untamed', name: 'Titan Gaming Untamed', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-athena-vs-ares', name: 'Titan Gaming Athena Vs Ares', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-lab-of-lunacy', name: 'Twist Gaming Lab Of Lunacy', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-wild-orbs', name: 'Titan Gaming Wild Orbs', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-immortal-lightning', name: 'Twist Gaming Immortal Lightning', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-jeffs-gems', name: 'Twist Gaming Jeffs Gems', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-poseidon-vs-apollo', name: 'Titan Gaming Poseidon Vs Apollo', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-biker-bucks', name: 'Twist Gaming Biker Bucks', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-festive-frost', name: 'Twist Gaming Festive Frost', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-slash', name: 'Titan Gaming Slash', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-krakens-curse', name: 'Twist Gaming Krakens Curse', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-skyship-raiders', name: 'Twist Gaming Skyship Raiders', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-brains-for-breakfast', name: 'Twist Gaming Brains For Breakfast', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-juice-monster', name: 'Titan Gaming Juice Monster', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-samurai-dogs-unleashed', name: 'Twist Gaming Samurai Dogs Unleashed', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-spin-reaper', name: 'Twist Gaming Spin Reaper', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-jade-fate', name: 'Twist Gaming Jade Fate', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-mining-mayhem', name: 'Twist Gaming Mining Mayhem', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-clash-of-fangs', name: 'Twist Gaming Clash Of Fangs', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-walking-wilds', name: 'Titan Gaming Walking Wilds', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-hercules-vs-hydra', name: 'Titan Gaming Hercules Vs Hydra', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-perseus-vs-medusa', name: 'Titan Gaming Perseus Vs Medusa', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-maximus', name: 'Titan Gaming Maximus', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-dragon-fiesta', name: 'Titan Gaming Dragon Fiesta', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-beasts-of-savannah', name: 'Titan Gaming Beasts Of Savannah', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-bluebeards-treasure', name: 'Twist Gaming Bluebeards Treasure', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-carp-diem', name: 'Twist Gaming Carp Diem', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-call-of-zuma', name: 'Titan Gaming Call Of Zuma', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-wild-savannah', name: 'Twist Gaming Wild Savannah', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-wallaby-wilds', name: 'Twist Gaming Wallaby Wilds', providerId: 'stakeEngine' },
  { slug: 'titan-gaming-plunder-bonanza', name: 'Titan Gaming Plunder Bonanza', providerId: 'stakeEngine' },
  { slug: 'twist-gaming-payback-posse', name: 'Twist Gaming Payback Posse', providerId: 'stakeEngine' },
  { slug: 'uppercut-phoenix-1000', name: 'Uppercut Phoenix 1000', providerId: 'stakeEngine' },
  { slug: 'paperclip-forged-in-plasma', name: 'Paperclip Forged In Plasma', providerId: 'stakeEngine' },
  { slug: 'paperclip-toon-pilot', name: 'Paperclip Toon Pilot', providerId: 'stakeEngine' },
  { slug: 'paperclip-dragonspire', name: 'Paperclip Dragonspire', providerId: 'stakeEngine' },
  { slug: 'paperclip-lazy-viking', name: 'Paperclip Lazy Viking', providerId: 'stakeEngine' },
  { slug: 'uppercut-crossfire', name: 'Uppercut Crossfire', providerId: 'stakeEngine' },
  { slug: 'paperclip-candy-rush', name: 'Paperclip Candy Rush', providerId: 'stakeEngine' },
  { slug: 'uppercut-mines-rush', name: 'Uppercut Mines Rush', providerId: 'stakeEngine' },
  { slug: 'paperclip-ritual', name: 'Paperclip Ritual', providerId: 'stakeEngine' },
  { slug: 'uppercut-vulcans-wrath', name: 'Uppercut Vulcans Wrath', providerId: 'stakeEngine' },
  { slug: 'uppercut-olympus-doubles', name: 'Uppercut Olympus Doubles', providerId: 'stakeEngine' },
  { slug: 'paperclip-afternoon-nap', name: 'Paperclip Afternoon Nap', providerId: 'stakeEngine' },
  { slug: 'uppercut-lost-forest', name: 'Uppercut Lost Forest', providerId: 'stakeEngine' },
  { slug: 'uppercut-kings-tribute', name: 'Uppercut Kings Tribute', providerId: 'stakeEngine' },
  { slug: 'paperclip-knight-shift', name: 'Paperclip Knight Shift', providerId: 'stakeEngine' },
  { slug: 'uppercut-mystery-circus', name: 'Uppercut Mystery Circus', providerId: 'stakeEngine' },
  { slug: 'paperclip-solar-eclipse', name: 'Paperclip Solar Eclipse', providerId: 'stakeEngine' },
  { slug: 'paperclip-round-robin', name: 'Paperclip Round Robin', providerId: 'stakeEngine' },
  { slug: 'paperclip-eggventure', name: 'Paperclip Eggventure', providerId: 'stakeEngine' },
  { slug: 'uppercut-wizard-shop', name: 'Uppercut Wizard Shop', providerId: 'stakeEngine' },
  { slug: 'paperclip-xmas-link', name: 'Paperclip Xmas Link', providerId: 'stakeEngine' },
  { slug: 'uppercut-gladiator-1000', name: 'Uppercut Gladiator 1000', providerId: 'stakeEngine' },
  { slug: 'paperclip-pigeon-mail', name: 'Paperclip Pigeon Mail', providerId: 'stakeEngine' },
  { slug: 'uppercut-wings-of-death', name: 'Uppercut Wings Of Death', providerId: 'stakeEngine' },
  { slug: 'paperclip-motor-ways', name: 'Paperclip Motor Ways', providerId: 'stakeEngine' },
  { slug: 'uppercut-samurai-1000', name: 'Uppercut Samurai 1000', providerId: 'stakeEngine' },
  { slug: 'knucklehead-the-family-death', name: 'Knucklehead The Family Death', providerId: 'stakeEngine' },
  { slug: 'uppercut-rise-of-asgard', name: 'Uppercut Rise Of Asgard', providerId: 'stakeEngine' },
  { slug: 'uppercut-pirate-doubles', name: 'Uppercut Pirate Doubles', providerId: 'stakeEngine' },
  { slug: 'paperclip-candy-party', name: 'Paperclip Candy Party', providerId: 'stakeEngine' },
  { slug: 'paperclip-konbini', name: 'Paperclip Konbini', providerId: 'stakeEngine' },
  { slug: 'uppercut-apex-protocol', name: 'Uppercut Apex Protocol', providerId: 'stakeEngine' },
  { slug: 'uppercut-snow-temple', name: 'Uppercut Snow Temple', providerId: 'stakeEngine' },
  { slug: 'paperclip-witchy-wilds', name: 'Paperclip Witchy Wilds', providerId: 'stakeEngine' },
  { slug: 'paperclip-forged-in-fire', name: 'Paperclip Forged In Fire', providerId: 'stakeEngine' },
  { slug: 'paperclip-farm-and-merge', name: 'Paperclip Farm And Merge', providerId: 'stakeEngine' },
  { slug: 'paperclip-manor-gray', name: 'Paperclip Manor Gray', providerId: 'stakeEngine' },
  { slug: 'knucklehead-flamin-hot-wings', name: 'Knucklehead Flamin Hot Wings', providerId: 'stakeEngine' },
  { slug: 'paperclip-scroll-keeper', name: 'Paperclip Scroll Keeper', providerId: 'stakeEngine' },
  { slug: 'knucklehead-shells-angels', name: 'Knucklehead Shells Angels', providerId: 'stakeEngine' },
  { slug: 'paperclip-bluebeards-ghost', name: 'Paperclip Bluebeards Ghost', providerId: 'stakeEngine' },
  { slug: 'paperclip-borrowed-time', name: 'Paperclip Borrowed Time', providerId: 'stakeEngine' },
  { slug: 'paperclip-deadspin-bonanza', name: 'Paperclip Deadspin Bonanza', providerId: 'stakeEngine' },
  { slug: 'knucklehead-sheikhs-vs-snakes', name: 'Knucklehead Sheikhs Vs Snakes', providerId: 'stakeEngine' },
  { slug: 'paperclip-crown-conquest', name: 'Paperclip Crown Conquest', providerId: 'stakeEngine' },
  { slug: 'paperclip-pinball-peak', name: 'Paperclip Pinball Peak', providerId: 'stakeEngine' },
  { slug: 'paperclip-knight-fall', name: 'Paperclip Knight Fall', providerId: 'stakeEngine' },
  { slug: 'paperclip-minedrop', name: 'Paperclip Minedrop', providerId: 'stakeEngine' },
  { slug: 'paperclip-red-robin', name: 'Paperclip Red Robin', providerId: 'stakeEngine' },
  { slug: 'paperclip-penguins-can-fly', name: 'Paperclip Penguins Can Fly', providerId: 'stakeEngine' },
  { slug: 'paperclip-maze-quest', name: 'Paperclip Maze Quest', providerId: 'stakeEngine' },
  { slug: 'paperclip-pinball-street', name: 'Paperclip Pinball Street', providerId: 'stakeEngine' },
  { slug: 'paperclip-balance', name: 'Paperclip Balance', providerId: 'stakeEngine' },
  { slug: 'sidequest-stupid-cupid', name: 'Stupid Cupid', providerId: 'stakeEngine' },
]

export const PROVIDERS = {
  hacksaw: { id: 'hacksaw', name: 'Hacksaw Gaming', impl: 'web' },
  stakeEngine: { id: 'stakeEngine', name: 'Stake Engine', impl: 'web' },
  avatarux: { id: 'avatarux', name: 'Avatarux', impl: 'web' },
  bgaming: { id: 'bgaming', name: 'BGaming', impl: 'web' },
  endorphina: { id: 'endorphina', name: 'Endorphina', impl: 'backend' },
  gamomat: { id: 'gamomat', name: 'Gamomat', impl: 'backend' },
  justslots: { id: 'justslots', name: 'Just Slots', impl: 'backend' },
  massive: { id: 'massive', name: 'Massive Studios', impl: 'backend' },
  octoplay: { id: 'octoplay', name: 'Octoplay', impl: 'backend' },
  onetouch: { id: 'onetouch', name: 'One Touch', impl: 'backend' },
  petersons: { id: 'peter-sons', name: 'Peter & Sons', impl: 'web' },
  playngo: { id: 'playngo', name: "Play'n GO", impl: 'backend' },
  popiplay: { id: 'popiplay', name: 'Popiplay', impl: 'backend' },
  pragmatic: { id: 'pragmatic', name: 'Pragmatic Play', impl: 'web' },
  push: { id: 'push', name: 'Push Gaming', impl: 'backend' },
  redtiger: { id: 'redtiger', name: 'Red Tiger', impl: 'backend' },
  relax: { id: 'relax', name: 'Relax Gaming', impl: 'backend' },
  shadylady: { id: 'shadylady', name: 'Shady Lady', impl: 'backend' },
  slotmill: { id: 'slotmill', name: 'Slotmill', impl: 'backend' },
  thunderkick: { id: 'thunderkick', name: 'Thunderkick', impl: 'webview' },
  truelab: { id: 'truelab', name: 'Truelab', impl: 'backend' },
  twist: { id: 'twist', name: 'Twist Gaming', impl: 'web' },
  nolimit: { id: 'nolimit', name: 'Nolimit City', impl: 'web' },
}

export function getWebReadySlots() {
  return SUPPORTED_SLOTS.filter((s) => {
    const impl = PROVIDERS[s.providerId]?.impl
    return impl === 'web' || impl === 'webview'
  })
}

/** Alle Slots (inkl. Backend-Provider, sobald Backend läuft) */
export function getAllSlots() {
  return SUPPORTED_SLOTS
}

/** Slots nach Anbieter gruppiert: { providerId: { provider, slots } } */
export function getSlotsGroupedByProvider(slots) {
  const groups = {}
  for (const slot of slots || []) {
    const pid = slot.providerId || 'other'
    if (!groups[pid]) {
      groups[pid] = { provider: PROVIDERS[pid] || { id: pid, name: pid }, slots: [] }
    }
    groups[pid].slots.push(slot)
  }
  return groups
}
